[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Alex Eagle", email = "alex@aspect.dev"},
]
dependencies = [
    "django~=4.2.0",
    "colorama~=0.4.0",
    "click",
    "pytest",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache-2"}


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
